// Reads real pixel dimensions for an image in public/ at build time, so
// <img> tags can carry explicit width/height and avoid layout shift while
// loading — without this, the browser doesn't know the image's aspect
// ratio until the file itself starts arriving.
import { existsSync } from 'node:fs';
import { join } from 'node:path';
import sharp from 'sharp';

const publicDir = join(process.cwd(), 'public');

export type PublicImageInfo = { width: number; height: number; ok: boolean };

const dimensionCache = new Map<string, Promise<PublicImageInfo>>();

// A single bad reference (an upload that failed partway, a file renamed/
// deleted after a project's data still points at the old name, a non-image
// file saved with an image extension) used to throw all the way up through
// Astro's build and fail the ENTIRE site, not just the one project with
// the bad reference — confirmed for real via two live build failures
// (alterkitektura-2024: "unsupported image format"; ruin-and-reverie:
// "Input file is missing") once Sveltia CMS went live and Leila started
// uploading directly. `ok: false` lets each page decide how to show that
// visibly (a "missing image" placeholder) instead of either crashing the
// whole build or silently rendering nothing wrong at all — a non-developer
// actively editing content needs some signal on the page itself that an
// image reference broke, not just a build-log warning nobody will read.
const FALLBACK_SIZE = { width: 1200, height: 900 };

export function getPublicImageSize(publicPath: string): Promise<PublicImageInfo> {
  const cached = dimensionCache.get(publicPath);
  if (cached) return cached;

  const promise = (async () => {
    const filePath = join(publicDir, publicPath);
    try {
      const { width, height } = await sharp(filePath).metadata();
      if (!width || !height) throw new Error('no dimensions in metadata');
      return { width, height, ok: true };
    } catch (err) {
      console.warn(`[image-size] Could not read "${publicPath}" (${(err as Error).message}) — rendering a missing-image placeholder instead.`);
      return { ...FALLBACK_SIZE, ok: false };
    }
  })();

  dimensionCache.set(publicPath, promise);
  return promise;
}

// Percent-encodes each path segment. Filenames here come straight from
// Leila's CMS uploads and routinely contain spaces ("TH PERSP 1.png"). In
// a plain src="" that's tolerated, but in srcset="" a space ends the URL
// and starts a descriptor — so "…/Graphic Design_POST 5-thumb.webp" was
// parsed as URL "…/Graphic" + junk descriptor, the whole candidate was
// dropped as invalid, and the browser silently fell back to the <img>'s
// original multi-megabyte PNG (confirmed: ~138MB downloaded scrolling the
// homepage, only filenames without spaces ever got their thumbnails).
// Commas would break srcset the same way (and # / ? would be read as a
// fragment/query), so those are encoded on top of encodeURI. Other
// reserved characters that are legal in a path (& ; = + $ @ :) are left
// alone on purpose: encoding them (e.g. "&" -> "%26") is correct on
// production hosting but 404s under Astro's dev server, which doesn't
// decode them when looking up the file.
function encodePublicPath(publicPath: string): string {
  return publicPath
    .split('/')
    .map((segment) => encodeURI(segment).replace(/[#?,]/g, (c) => '%' + c.charCodeAt(0).toString(16).toUpperCase()))
    .join('/');
}

// The compressed sibling scripts/compress-images.mjs generates next to each
// source image in public/images/curated (same path, .webp extension).
// Returned URL-encoded, ready for src/srcset — don't use it for filesystem
// access.
export function toWebpPath(publicPath: string): string {
  return encodePublicPath(publicPath.replace(/\.(png|jpe?g)$/i, '.webp'));
}

// Prefer the compressed sibling generated by compress-images.mjs, but keep
// the original source usable in dev when that prebuild step has not run.
export function toOptimizedPublicImagePath(publicPath: string): string {
  const webpPath = publicPath.replace(/\.(png|jpe?g)$/i, '.webp');
  return webpPath !== publicPath && existsSync(join(publicDir, webpPath))
    ? encodePublicPath(webpPath)
    : encodePublicPath(publicPath);
}

// Browser icons are rendered at a small square size even when the CMS source
// is a full-resolution PNG. Returning a data URI avoids adding generated
// files to public/ while keeping the favicon tied to the CMS asset.
export async function getPublicFaviconDataUri(publicPath: string): Promise<string | null> {
  const imageInfo = await getPublicImageSize(publicPath);
  if (!imageInfo.ok) return null;

  try {
    const filePath = join(publicDir, publicPath);
    const favicon = await sharp(filePath)
      .resize(64, 64, {
        fit: 'contain',
        background: { r: 0, g: 0, b: 0, alpha: 0 },
      })
      .png()
      .toBuffer();
    return `data:image/png;base64,${favicon.toString('base64')}`;
  } catch (err) {
    console.warn(`[image-size] Could not create a favicon from "${publicPath}" (${(err as Error).message}) — using the default favicon instead.`);
    return null;
  }
}

// A much smaller (640px-wide-capped) sibling, also generated by
// compress-images.mjs, for contexts where the image is only ever shown as
// a small tile (homepage grid cards, gallery thumbnails) — using the full
// 2000px .webp there was wasted bandwidth/decode time for something
// displayed at a fraction of that size. Use toWebpPath() instead for the
// lightbox's actual zoomed-in view, which does need the larger version.
export function toThumbPath(publicPath: string): string {
  return toWebpPath(publicPath).replace(/\.webp$/, '-thumb.webp');
}

const THUMB_WIDTH = 640;
const MID_WIDTH = 1200;

// srcset for grid cards and gallery tiles: 640px thumb, 1200px mid-size
// (only if the source is wider) and the full .webp. Paired with a sizes=
// that reflects the tile's real layout width, so a 1x laptop gets the
// size it actually needs and a phone/retina screen gets a sharper one —
// the thumb alone was visibly upscaled (a full-width gallery tile is
// ~1400 CSS px). Keep widths in sync with compress-images.mjs.
export function toTileSrcSet(publicPath: string, sourceWidth: number): string {
  const entries = [`${toThumbPath(publicPath)} ${Math.min(sourceWidth, THUMB_WIDTH)}w`];
  if (sourceWidth > MID_WIDTH) {
    const midFile = publicPath.replace(/\.(png|jpe?g)$/i, `-${MID_WIDTH}.webp`);
    if (existsSync(join(publicDir, midFile))) entries.push(`${encodePublicPath(midFile)} ${MID_WIDTH}w`);
  }
  if (sourceWidth > THUMB_WIDTH) entries.push(`${toWebpPath(publicPath)} ${Math.min(sourceWidth, FULL_WIDTH)}w`);
  return entries.join(', ');
}

// Intermediate widths compress-images.mjs generates for project heroes
// only (keep in sync with HERO_WIDTHS there). The hero spans the full
// viewport width, so a phone (~390 CSS px x 3 DPR) needs ~1200px, a
// laptop ~1440-1600px, and only very wide/retina screens benefit from the
// full 2000px file.
const HERO_WIDTHS = [1200, 1600];
const FULL_WIDTH = 2000;

// srcset for a project hero: whichever of the -1200/-1600 variants exist on
// disk (they're skipped for sources already narrower than that width),
// plus the full-size .webp, labelled with its real pixel width. Callers
// pair it with sizes="100vw".
export function toHeroSrcSet(publicPath: string, sourceWidth: number): string {
  const webp = publicPath.replace(/\.(png|jpe?g)$/i, '.webp');
  const entries: string[] = [];
  for (const w of HERO_WIDTHS) {
    if (sourceWidth <= w) continue;
    const variant = webp.replace(/\.webp$/, `-${w}.webp`);
    if (existsSync(join(publicDir, variant))) entries.push(`${encodePublicPath(variant)} ${w}w`);
  }
  entries.push(`${encodePublicPath(webp)} ${Math.min(sourceWidth, FULL_WIDTH)}w`);
  return entries.join(', ');
}
